spring:
  data:
    redis:
      database: 2
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}
      timeout: 30000

  cloud:
    nacos:
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      discovery:
        server-addr: nacos:8848

    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 60000
            response-timeout: 60000

          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowedOriginPatterns:
                  - "*"
                allowedMethods:
                  - "GET"
                  - "POST"
                  - "PUT"
                  - "DELETE"
                  - "PATCH"
                  - "OPTIONS"
                allowedHeaders: "*"
                allowCredentials: true
                maxAge: 36000

          routes:
            - id: UserService
              uri: lb://UserService
              predicates:
                - Path=/api/user/**,/api/contact/**,/api/group/**

            - id: OfflineDataService
              uri: lb://OfflineDataService
              predicates:
                - Path=/api/message/**

            - id: AiService
              uri: lb://AiService
              predicates:
                - Path=/api/ai/**

            - id: RedPacketService
              uri: lb://RedPacketService
              predicates:
                - Path=/api/chat/redPacket/**