spring:
  data:
    redis:
      host: IP
      port: 59000
      password: e65K4t8w2
      ttl: 3600
      timeout: 30000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://IP:49152/InfiniteChat?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: gK3T9n%q2M@j7Z4
  cloud:
    nacos:
      discovery:
        server-addr: localhost:18375
pgvector:
  database: dp
  host: IP
  port : 54328
  user: root
  password: e65K4t7z1
  table: dp_embedding

rag:
  docs-path: AiService/src/main/resources/docs