spring:
  data:
    redis:
      host: xxxxxx
      port: 59000
      password: e65K4t8w2
      ttl: 3600
      timeout: 30000

pgvector:
  database: dp
  host: xxxxx
  port : 54328
  user: root
  password: e65K4t7z1
  table: agent_embedding


rag:
  docs-path: /data/docs