spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:49152/InfiniteChat?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: ${MYSQL_ROOT_PASSWORD}

  data:
    redis:
      host: 127.0.0.1
      port: 59000
      password: ${REDIS_PASSWORD}

  kafka:
    bootstrap-servers: 127.0.0.1:9092

  cloud:
    nacos:
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      discovery:
        server-addr: 127.0.0.1:18375