spring:
  application:
    name: RedPacketService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://IP:49152/InfiniteChat?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: gK3T9n%q2M@j7Z4
  data:
    redis:
      database: 2
      host: IP
      port: 59000
      password: e65K4t8w2
      timeout: 30000

server:
  port: 8103