spring:
  application:
    name: RealTimeService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:49152/InfiniteChat?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: gK3T9n%q2M@j7Z4
  data:
    redis:
      database: 2
      host: localhost
      port: 59000
      password: e65K4t8w2
      timeout: 30000
  kafka:
    bootstrap-servers: localhost:9092  # Kafka 服务地址，多个用逗号分隔
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
    consumer:
      group-id: infinite-chat-push-group                # 消费者组 ID
      auto-offset-reset: earliest       # earliest / latest / none
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true          # 是否自动提交 offset
      auto-commit-interval: 1000        # 自动提交间隔（毫秒）
  cloud:
    nacos:
      discovery:
        server-addr: localhost:18375



server:
  port: 8102

snowflake:
  workerId: 1
  datacenterId: 1